name: 
channels:
  - conda-forge
  - openastronomy
  - astropy
  - auto
dependencies:
  - python
  - nbgitpuller
  - matplotlib
  - basemap
  - scipy
  - pandas
  - astropy
  - astroml
  - skyfield
  - aplpy
  - pyregion
  - pyephem
  - jplephem
  - sgp4
  - astroquery
  - poliastro
  - pysolar
  - sunpy
  - cartopy
  - pyproj
  - pip:
    - ipywidgets
    - pyavm
    - montage-wrapper
    - pdsimage
    - pyhorizon
    - orbitalpy
    - watermark
