#!/bin/bash

#Base box post build commands below here

jupyter contrib nbextension install --user
jupyter nbextension enable widgetsnbextension
jupyter nbextension enable python-markdown/main 
jupyter nbextension enable spellchecker/main
jupyter nbextension enable collapsible_headings/main
jupyter nbextension enable toc2/main
jupyter nbextension enable freeze/main
jupyter nbextension enable table_beautifier/main
jupyter nbextension enable highlighter/highlighter
jupyter nbextension enable equation-numbering/main
jupyter nbextension enable hide_input/main
jupyter nbextension enable hide_input_all/main
jupyter nbextension enable export_embedded/main

jupyter-nbextension install rise --py --user
jupyter-nbextension enable rise  --py --user 

jupyter-nbextension install jupyter_wysiwyg --py --user
jupyter nbextension enable jupyter_wysiwyg  --py --user 


# From https://github.com/binder-examples/latex/
# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
	
#Test that the test file exists
test -e test.png && rm test.png

jupyter labextension install @jupyterlab/latex
jupyter lab build
